# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 30, 791, 531))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(260, 0, 81, 31))
        self.label.setObjectName("label")
        self.City_box = QtWidgets.QComboBox(self.centralwidget)
        self.City_box.setEnabled(True)
        self.City_box.setGeometry(QtCore.QRect(340, 0, 81, 31))
        self.City_box.setStyleSheet("QComboBox{\n"
"    color: rgb(255,255,255);\n"
"}\n"
"\n"
"QComboBox:items{\n"
"    color: rgb(255,255,255);\n"
"}\n"
"\n"
"QListView{\n"
"    color: rgb(255,255,255);;\n"
"}   ")
        self.City_box.setObjectName("City_box")
        self.City_box.addItem("")
        self.City_box.addItem("")
        self.City_box.addItem("")
        self.City_box.addItem("")
        self.City_box.addItem("")
        self.City_box.addItem("")
        self.City_box.addItem("")
        self.City_box.addItem("")
        self.City_box.addItem("")
        self.City_box.addItem("")
        self.City_box.addItem("")
        self.City_box.addItem("")
        self.City_box.addItem("")
        self.City_box.addItem("")
        self.City_box.addItem("")
        self.City_box.addItem("")
        self.City_box.addItem("")
        self.City_box.addItem("")
        self.City_box.addItem("")
        self.City_box.addItem("")
        self.City_box.addItem("")
        self.City_box.addItem("")
        self.City_box.addItem("")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 251, 23))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.male = QtWidgets.QRadioButton(self.layoutWidget)
        self.male.setObjectName("male")
        self.horizontalLayout.addWidget(self.male)
        self.female = QtWidgets.QRadioButton(self.layoutWidget)
        self.female.setObjectName("female")
        self.horizontalLayout.addWidget(self.female)
        self.total = QtWidgets.QRadioButton(self.layoutWidget)
        self.total.setChecked(True)
        self.total.setObjectName("total")
        self.horizontalLayout.addWidget(self.total)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "台灣各縣市小額終老保險投保率"))
        self.label.setText(_translate("MainWindow", "請選擇縣市"))
        self.City_box.setItemText(0, _translate("MainWindow", "全國"))
        self.City_box.setItemText(1, _translate("MainWindow", "台北市"))
        self.City_box.setItemText(2, _translate("MainWindow", "新北市"))
        self.City_box.setItemText(3, _translate("MainWindow", "基隆市"))
        self.City_box.setItemText(4, _translate("MainWindow", "桃園市"))
        self.City_box.setItemText(5, _translate("MainWindow", "新竹縣"))
        self.City_box.setItemText(6, _translate("MainWindow", "新竹市"))
        self.City_box.setItemText(7, _translate("MainWindow", "苗栗縣"))
        self.City_box.setItemText(8, _translate("MainWindow", "台中市"))
        self.City_box.setItemText(9, _translate("MainWindow", "彰化縣"))
        self.City_box.setItemText(10, _translate("MainWindow", "南投縣"))
        self.City_box.setItemText(11, _translate("MainWindow", "雲林縣"))
        self.City_box.setItemText(12, _translate("MainWindow", "嘉義縣"))
        self.City_box.setItemText(13, _translate("MainWindow", "嘉義市"))
        self.City_box.setItemText(14, _translate("MainWindow", "台南市"))
        self.City_box.setItemText(15, _translate("MainWindow", "高雄市"))
        self.City_box.setItemText(16, _translate("MainWindow", "屏東縣"))
        self.City_box.setItemText(17, _translate("MainWindow", "宜蘭縣"))
        self.City_box.setItemText(18, _translate("MainWindow", "花蓮縣"))
        self.City_box.setItemText(19, _translate("MainWindow", "台東縣"))
        self.City_box.setItemText(20, _translate("MainWindow", "澎湖縣"))
        self.City_box.setItemText(21, _translate("MainWindow", "金門縣"))
        self.City_box.setItemText(22, _translate("MainWindow", "連江縣"))
        self.male.setText(_translate("MainWindow", "男"))
        self.female.setText(_translate("MainWindow", "女"))
        self.total.setText(_translate("MainWindow", "總計"))
